name: CI_TrubchaninovNikita_Group123
on:
  push:
    branches: [ "main", "master", "dev" ]  # Гілка dev створена додатково

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_SHARED_LIBS=OFF

    - name: Build project
      run: |
        cd build
        cmake --build . --config Release

    - name: Run executable
      run: |
        cd build
        ./tic_tac_toe